# Generated by Django 6.0 on 2026-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('country', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['-created_ts'],
            },
        ),
    ]
