# Generated by Django 6.0 on 2026-04-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_ts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='modified_ts',
        ),
    ]
