# Generated by Django 6.0 on 2026-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_remove_employee_created_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Engineering Manager', 'Engineering Manager'), ('Data Analyst', 'Data Analyst'), ('Product Manager', 'Product Manager'), ('HR Manager', 'HR Manager')], max_length=150),
        ),
    ]
