# Generated by Django 6.0 on 2026-04-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('SOFTWARE_ENGINEER', 'Software Engineer'), ('SENIOR_SOFTWARE_ENGINEER', 'Senior Software Engineer'), ('ENGINEERING_MANAGER', 'Engineering Manager'), ('DATA_ANALYST', 'Data Analyst'), ('PRODUCT_MANAGER', 'Product Manager'), ('HR_MANAGER', 'HR Manager')], max_length=24),
        ),
    ]
