# Generated by Django 6.0 on 2026-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_department_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(choices=[('UNITED_STATES', 'United States'), ('INDIA', 'India'), ('UNITED_KINGDOM', 'United Kingdom'), ('GERMANY', 'Germany'), ('CANADA', 'Canada'), ('AUSTRALIA', 'Australia')], max_length=14),
        ),
    ]
