from apps.employee.constants import Country, Department, EMPLOYEE_SALARY_MAX_VALUE, EMPLOYEE_SALARY_MIN_VALUE, JobTitle

"""
Employee test data constants start.
"""

TEST_EMPLOYEE_ID = "EMP0000000001"
TEST_EMPLOYEE_NAME = "John Doe"
TEST_EMPLOYEE_EMAIL = "john.doe@example.com"
TEST_EMPLOYEE_JOB_TITLE = JobTitle.SOFTWARE_ENGINEER
INVALID_JOB_TITLE = "Invalid Job Title"
MISMATCHED_JOB_TITLE = JobTitle.ENGINEERING_MANAGER
TEST_EMPLOYEE_DEPARTMENT = Department.ENGINEERING
INVALID_DEPARTMENT = "Invalid Department"
MISMATCHED_DEPARTMENT = Department.MANAGEMENT
TEST_EMPLOYEE_SALARY = 50000
NEGATIVE_SALARY = -1
SALARY_BELOW_MINIMUM = EMPLOYEE_SALARY_MIN_VALUE - 1
SALARY_ABOVE_MAXIMUM = EMPLOYEE_SALARY_MAX_VALUE + 1
TEST_EMPLOYEE_JOINING_DATE = "2024-01-15"
JOINING_DATE_BEFORE_MIN = "1900-12-31"
JOINING_DATE_AT_MIN = "1901-01-01"
TEST_EMPLOYEE_COUNTRY = Country.INDIA
INVALID_COUNTRY = "Invalid Country"

NONEXISTENT_EMPLOYEE_PK = 99999

EMPLOYEE_SEARCH_QUERY = "John"
EMPLOYEE_EMAIL_SEARCH_QUERY = "john.doe"
EMPLOYEE_ID_SEARCH_QUERY = "EMP0000000001"

OTHER_EMPLOYEE_ID = "EMP0000000002"
OTHER_EMPLOYEE_NAME = "Jane Smith"
OTHER_EMPLOYEE_EMAIL = "jane.smith@example.com"

DELETED_EMPLOYEE_ID = "EMP0000000003"
DELETED_EMPLOYEE_EMAIL = "deleted.employee@example.com"
OTHER_EMPLOYEE_JOB_TITLE = JobTitle.HR_MANAGER
OTHER_EMPLOYEE_DEPARTMENT = Department.HR
OTHER_EMPLOYEE_COUNTRY = Country.UNITED_STATES
OTHER_EMPLOYEE_SALARY = 80000

UPDATED_EMPLOYEE_NAME = "Jane Doe"
UPDATED_EMPLOYEE_SALARY = 60000

FIRST_AUTO_GENERATED_EMPLOYEE_ID = "EMP1"
TEST_AUTO_GENERATED_EMAIL = "emp_1@incubyte.com"

"""
Employee test data constants end.
"""


"""
Employee query param constants start.
"""

SALARY_MIN_QUERY_PARAM = "salary_min"
SALARY_MAX_QUERY_PARAM = "salary_max"
SEARCH_QUERY_PARAM = "search"
PAGE_QUERY_PARAM = "page"

"""
Employee query param constants end.
"""


"""
Employee response key constants start.
"""

EMPLOYEE_ID_FIELD = "employee_id"
IS_ACTIVE_FIELD = "is_active"
NAME_FIELD = "name"
EMAIL_FIELD = "email"
JOB_TITLE_FIELD = "job_title"
DEPARTMENT_FIELD = "department"
SALARY_FIELD = "salary"
JOINING_DATE_FIELD = "joining_date"
COUNTRY_FIELD = "country"
DATA_KEY = "data"
RESULTS_KEY = "results"
COUNT_KEY = "count"
MIN_SALARY_FIELD = "min_salary"
MAX_SALARY_FIELD = "max_salary"
AVG_SALARY_FIELD = "avg_salary"
TOTAL_EMPLOYEES_FIELD = "total_employees"

"""
Employee response key constants end.
"""
